FROM node:18-alpine As production
RUN mkdir /app
COPY package.json /app/
WORKDIR /app
COPY . ./

ENV NEXT_PUBLIC_APP_URL=https://cloudforge-assessment.vercel.app/

RUN npm install
RUN npm run build
EXPOSE 4000
CMD ["npm", "run","start"]
