FROM node:20.9.0-bullseye-slim As production
RUN mkdir /app
COPY package.json /app/
WORKDIR /app
COPY . ./

ENV NEXT_PUBLIC_APP_URL=https://backend-558648895595.us-east1.run.app

RUN npm install
RUN npm run build
EXPOSE 4000
CMD ["npm", "run","start"]
